In [1]:
# data encoding >> converting categorical column into numerical
# nominal/OHE
# label and ordinal encoding
# target giudes ordinal encoding

In [2]:
# Nominal/OHE >> Binary vector for each of the categories
# example single, married, separated
# single: [1, 0, 0]
# married: [0, 1, 0]
# seperated: [0, 0, 1]

In [20]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [21]:
df = pd.DataFrame({'status': ['single', 'married', 'seperated', 'single', 'married']})

In [22]:
df

status
0     single
1    married
2  seperated
3     single
4    married

In [23]:
encoder = OneHotEncoder()

In [24]:
encoded = encoder.fit_transform(df[['status']]).toarray() # fit will try to learn which are the unique values and then just simply apply

In [25]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [26]:
encoder.get_feature_names_out()

array(['status_married', 'status_seperated', 'status_single'],
      dtype=object)

In [27]:
encoder_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [15]:
encoder_df

status_married  status_seperated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             1.0               0.0            0.0

In [28]:
# if new data comes
encoder.transform([['single']]).toarray()

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [29]:
# pd.get_dummies() h/w
# same thing you can achive using this function

In [30]:
pd.concat([df, encoder_df], axis = 1)

status  status_married  status_seperated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  seperated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4    married             1.0               0.0            0.0

In [35]:
import seaborn as sns
df = sns.load_dataset('tips')

In [40]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['day']]).toarray()
encoded
encoder.get_feature_names_out()
encoded_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [41]:
encoded_df

day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [42]:
pd.concat([df, encoded_df])

total_bill   tip     sex smoker  day    time  size  day_Fri  day_Sat  day_Sun  day_Thur
0         16.99  1.01  Female     No  Sun  Dinner   2.0      NaN      NaN      NaN       NaN
1         10.34  1.66    Male     No  Sun  Dinner   3.0      NaN      NaN      NaN       NaN
2         21.01  3.50    Male     No  Sun  Dinner   3.0      NaN      NaN      NaN       NaN
3         23.68  3.31    Male     No  Sun  Dinner   2.0      NaN      NaN      NaN       NaN
4         24.59  3.61  Female     No  Sun  Dinner   4.0      NaN      NaN      NaN       NaN
..          ...   ...     ...    ...  ...     ...   ...      ...      ...      ...       ...
239         NaN   NaN     NaN    NaN  NaN     NaN   NaN      0.0      1.0      0.0       0.0
240         NaN   NaN     NaN    NaN  NaN     NaN   NaN      0.0      1.0      0.0       0.0
241         NaN   NaN     NaN    NaN  NaN     NaN   NaN      0.0      1.0      0.0       0.0
242         NaN   NaN     NaN    NaN  NaN     NaN   NaN      0.0      1.0      0.0       0.0
243         NaN   NaN     NaN    NaN  NaN     NaN   NaN      0.0      0.0      0.0       1.0

[488 rows x 11 columns]

In [ ]:
# label encoding >> assign unique labels to the categories

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [44]:
df = pd.DataFrame({'status': ['single', 'married', 'seperated', 'single', 'married']})

In [46]:
df

status
0     single
1    married
2  seperated
3     single
4    married

In [ ]:
# using map or using library

In [47]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [48]:
label_encoder.fit_transform(df[['status']])

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [49]:
label_encoder.transform([['seperated']])

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [51]:
# ordinal encoding

# high school : 1
# graduate : 2
# post graduate : 3
# phd : 4

In [52]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({'qualification' : ["HS", "GR", "PG", "PHD", "HS", "PHD"]})

In [53]:
encoder = OrdinalEncoder(categories=[["HS", "GR", "PG", "PHD"]])

In [54]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [55]:
encoder.transform([['GR']])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[1.]])

In [57]:
# target guided ordianl encoding
# encoding based on some relationship with target variables
# used when a lot of uniqye categories are there
# replace the category with mean and median of respective group

In [59]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [60]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [63]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [64]:
df['time_encoded'] = df['time'].map(mean_price)

In [65]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333

In [66]:
# one last thing
# what is sklearn >> sklearn is called as sckit learn library which actually deals with machine learning and inside this library there is a module sklearn.preprocessing